spring.application.name=api


# Configura a porta da aplicação
server.port=8888


# Desabilita (por enquanto) o acesso a banco de dados

spring.datasource.url=jdbc:postgresql://pooled.db.prisma.io:5432/postgres?sslmode=require
spring.datasource.username=5d6439ca1943eef9fb1607f7b8206a7225e107637789c9c477daa4d518357960
spring.datasource.password=sk_Sk3xoNvKEXgh93Or2y5CU

